defaults:
- base

run_name: scenario_dreamer_ldm_base_waymo # default run name for evaluation

mode: initial_scene # or lane_conditioned or inpainting or metrics
num_samples: 100 # number of samples to generate during evaluation
init_prob_matrix_path: ${project_root}/metadata/initial_prob_matrix_waymo.pt # path to initial scene num lanes and agents probability matrix
inpainting_prob_matrix_path: ${project_root}/metadata/inpainting_prob_matrix_waymo.pt # path to inpainting num lanes and agents probability matrix
batch_size: 32 # batch size for evaluation
visualize: False # visualize samples during evaluation?
viz_dir: ${project_root}/viz_gen_samples_${ldm.eval.run_name} # directory to save visualizations of generated samples
cache_samples: False # cache samples to disk?
conditioning_path: null # optional path to conditioning data for lane-conditioned or inpainting evaluation

metrics:
  samples_path: ${dataset_root}/checkpoints/${ldm.eval.run_name}/samples # path to load generated samples
  metrics_save_path: ${dataset_root}/checkpoints/${ldm.eval.run_name} # path to save metrics
  eval_set: ${project_root}/metadata/waymo_eval_set.pkl # pickle containing paths to ground-truth samples for metrics computation
  gt_test_dir: ${dataset_root}/scenario_dreamer_ae_preprocess_waymo/test # directory containing ground-truth agent/lane data for metrics computation