defaults:
- base

_target_: datamodules.nuplan.nuplan_datamodule_autoencoder3d.nuplan_datamodule_autoencoder3d_temp.NuplanDataModuleAutoEncoder3DTemp

train_batch_size: 128
val_batch_size: 128
dataset_cfg: null

