defaults:
- base

_target_: datamodules.nuplan.nuplan_datamodule_ldm3d_image.NuplanDataModuleLDM3D

train_batch_size: 2 # TODO: 2 for debugging, 256 for original, but it's impossible to load so many images
val_batch_size: 2 # TODO: 2 for debugging, 256 for original
dataset_cfg: null